### PR TITLE
Begin OS X support

### PR DESCRIPTION
**Pull request by 0joshuaolson1**
It compiles and runs. I successfully tested:
- changing settings
- exiting
- looking, moving/jumping, and mining
- inventory screen
- saving and reloading universes

I encounter (EDIT: 1 bug) bugs in the universe slot selection screen:
- I can't leave with Escape. I have to load a game and exit from there

### CODE REVIEW

**Comment by Blackvoxel** [comment]
Oh, that's fine !
Thanks for this beginning of Mac port. 
We'll wait your greenlight for merging.

**Comment by 0joshuaolson1** [comment]
I had it working minutes ago from within NetBeans's terminal, but now from the standard terminal the program won't start, saying
```

```
By the way, the src/z/ZTypes.h diff looks way bigger than it should be. I only added the lines
```
#elif __APPLE__ && __MACH__
#  define ZENV_OS_OSX
```

**Comment by 0joshuaolson1** [comment]
Aaaaand I figured out why. Fixing...

**Comment by Blackvoxel** [comment]
Fine !

**Comment by 0joshuaolson1** [comment]
This is as far as I'll be getting. It's still possible to run in one terminal while failing somehow in another. My guess is something about environment variables.

**Comment by Blackvoxel** [comment]
Does it fail like above with the error 1070.3 ?
When running, do you see any saved files ?
If it hangs when pressing escape, maybe something prevent a thread from exiting.

**Comment by 0joshuaolson1** [comment]
Yes, same failure. I didn't figure out why, I just noticed that I missed something and hoped that it was the fix.

It takes several seconds from launch to exit with the error, not displaying the first image as it should even though it's in the correct place and presumably with the right file permissions.

Would there be any saved files at this early point in the program launch?

**Comment by Blackvoxel** [comment]
At the point 1070, there is not yet saved files apart the log.txt
The 1070.3 error is coming directly from the failure of the function TextureManager.LoadBMPTexture() in this line [here](https://github.com/Blackvoxel/Blackvoxel/blob/master/src/ZGame.cpp#L363). Despite the appearance, this second line is the first one to load as the first line isn't executed.
Fortunately, this let us with very few case of possible errors. As we have written all the underlying toolkits (and the bmp loading function) ([here](https://github.com/Blackvoxel/Blackvoxel/blob/master/src/z/ZBitmapImage.cpp#L87)), the case of errors are very limited :
-Out of memory
-Can't open or read in the file.
-Error in the format of data in the file.
I suggest to put a breakpoint on this line and to trace from here. There may some good chance it will get an error on the fopen() function in ZBitmapImage::LoadBMP().

**Comment by 0joshuaolson1** [comment]
Hey, slots show 'USED' after the last try! I'm try to reproduce the image loading failure in my IDE with the breakpoint. Thanks for helping.

I wonder if [#13}(13) is related...

**Comment by Blackvoxel** [comment]
No, it shouldn't be related because the symptoms are different.
The case related to the '13' is not really a bug. It happens when Blackvoxel didn't find it's asset files because these are not present (or not present at the location it is intended). 
The first file to be loaded by Blackvoxel is the high quality random number file randomnum.dat. 
What happens in case this file is missing arise in [this line](https://github.com/Blackvoxel/Blackvoxel/blob/master/src/z/ZFastRandom.cpp#L50).  
When the randomnum.dat file is not found, a message "Error loading random file" is displayed and an exception is thrown, terminating the program.  
The behaviour of this part is not a bug. But the message should be more explicit. This part of code is obsolete and must be reworked to be integrated with the central log system. (Note : the proposed patch to 13 have several flaws, don't use it. )
In your case, if you got error 1070.3, this indicate that the program have already passed this point. This mean that (at least) some of the files was found.
In the ACompileSettings.h, you set COMPILEOPTION_DATAFILESPATH to "". This is the right setting when the asset files are stored at the same location than the executable. With this setting, Blackvoxel use relative path and the asset files are searched in the Blackvoxel directory (and subdirectories).
In your case, the symptoms shown that the randomnum.dat(which is at the root of the Blackvoxel directory can be loaded, but that the gui/title_2_0.bmp file can't be loaded.

So what I suggest to do :
- Double check the access rights for the "gui" subdirectory and the permissions of the files in it.
- Put a printf("LoadBMP() file : %s\n"); [here](https://github.com/Blackvoxel/Blackvoxel/blob/master/src/z/ZBitmapImage.cpp#L116) in order to check the path and filename used to open the file.
- At the same place, printf the result of the getcwd() command to check what it the starting point of the relative path access attempts.

About the "Used" mark, this is a [check](https://github.com/Blackvoxel/Blackvoxel/blob/master/src/ZScreen_SlotSelection.cpp#L127) to the existence of PlayerInfo.dat file in the universe directory. If this file is missing, this could indicate that the save process failed when pressing escape. This could also come from a problem of rights in writing the files.
You suspected a problem of environment variables, I think the behaviour of [this function](https://github.com/0joshuaolson1/Blackvoxel/blob/master/src/z/ZStream_File.cpp#L538) should be checked.
Thanks for your efforts in making this port.
The Blackvoxel Team

**Comment by 0joshuaolson1** [comment]
That was very helpful. When it works (I print `FileName`, then the path, then do `fflush(stdout)`:
```
LoadBMP() file : VoxelTypes/voxeltexture_255.bmp
LoadBMP() path : /Users/0joshuaolson1/blackvoxel
LoadBMP() file : VoxelTypes/voxeltexture_256.bmp
LoadBMP() path : /Users/0joshuaolson1/blackvoxel
LoadBMP() file : /Users/0joshuaolson1/Blackvoxel/UserTextures/voxeltexture_1.bmp
LoadBMP() path : /Users/0joshuaolson1/blackvoxel
LoadBMP() file : gui/title_2_0.bmp
LoadBMP() path : /Users/0joshuaolson1/blackvoxel
```
When it doesn't:
```
LoadBMP() file : VoxelTypes/voxeltexture_244.bmp
LoadBMP() path : /Users/0joshuaolson1/blackvoxel
LoadBMP() file : VoxelTypes/voxeltexture_245.bmp
LoadBMP() path : /Users/0joshuaolson1/blackvoxel
LoadBMP() file : /Users/0joshuaolson1/Blackvoxel/UserTextures/voxeltexture_1.bmp
LoadBMP() path : /Users/0joshuaolson1/blackvoxel
LoadBMP() file : gui/title_2_0.bmp
LoadBMP() path : 
[1070.3] *** ERROR : Missing gui texture file gui/title_2_0.bmp
```
Besides the path becoming "", the textures beyond 245 aren't loaded. That's odd.

**Comment by Blackvoxel** [comment]
Obviously, there is something broken as we never encountered this behaviour on Windows and Linux, even when doing the PI port. 
But we know that an environment difference can always trigger an hidden bug or make something fail.
To start investigating, I've browsed all your changes carefully to see if something could introduce such a bug, I but found nothing. 
At least, we can estimate to be happy that this problem arise in an early launching stage where a limited amount of code is involved.
So, some suggestions coming to my mind for refining the field of search :
- Try compiling with -O0 -g3 and see if something change.
- Remove the Voxeltexture 244 and 245 from the VoxelTypes directory to see what happens (don't forget to put these back after).
- Try changing the launching order of the texture manager and the voxeltype manager. To do so, simply exchange the two following lines [here](https://github.com/Blackvoxel/Blackvoxel/blob/master/src/ZGame.h#L479) and see what happens.
- Which compiler does your system use ? g++ or llvm ? I'know nothing on the Mac, but found [that link](https://stackoverflow.com/questions/19535422/os-x-10-9-gcc-links-to-clang) suggesting that llvm is used even when invoking g++. We have not yet tried to compile Blackvoxel with llvm.

The Blackvoxel Team

**Comment by Blackvoxel** [comment]
Ok, I think I got it.
Just after [this line](https://github.com/Blackvoxel/Blackvoxel/blob/master/src/z/ZBitmapImage.cpp#L224), add the following : fclose(fh);
I'll explain in a few hours what's happening.
The Blackvoxel Team.

**Comment by 0joshuaolson1** [comment]
That was the answer! I made the fix, so go ahead and merge.

I still have the escape key problem in the slot selector (but nowhere else).

Also, I tested with gcc 4.9, 5, and 6 (without your fix) with the same conditional 1070.3 error. All I had to do to make your code work with llvm was add the 'const' in `const ULong NumLines = 8;` in src/ZScreen_Options_Keymap.cpp. Of course, Linux and Windows won't have g++/gcc linked to clang++/clang (3.9). And I haven't tried with clang 4.0 (I could it you want).

Another note: I see a deprecation warning [probably related to SDL audio](https://github.com/kcat/openal-soft/issues/20):
```
2017-06-06 07:28:01.139 blackvoxel[11398:34550] 07:28:01.139 WARNING:  140: This application, or a library it uses, is using the deprecated Carbon Component Manager for hosting Audio Units. Support for this will be removed in a future release. Also, this makes the host incompatible with version 3 audio units. Please transition to the API's in AudioComponent.h.
```
But maybe instead there's an alternative to Cocoa I should've linked to in the Makefile? I don't know, but I'm on OS X 10.11.6, so I don't know when in future OS X releases this would become a problem.

**Comment by Blackvoxel** [comment]
Ok, that's very fine and it's a good news ! 
Thanks Joshua ! 
I look at that now.

**Comment by 0joshuaolson1** [comment]
You're welcome. Have fun writing a release announcement? ;P

**Comment by Blackvoxel** [comment]
Ok, we've checked all. The pull request is well written and clean. We are merging. :)

Yes, we'll do an announcement in the next days. We would like to thank you in this announcement. Do you agree we mention your name in it ?

Also, as a contributor, we should add you in the Contributors.txt. 
After we push the merge, can you fill it and submit a new pull request for the updated Contributors.txt ?
 
For the "deprecation" future issue, this is not a problem for now, so it's ok. We have time to look at it (for now, we don't want to move yet from SDL 1.2 for some good reasons). The day where we'll know the deadline for the problem, we can see. This day, there is likely to have some updated library available.

Some explanations I promised on the bug :
As your informations shown that files can't be read after some point, and worse, even getcwd() wasn't working anymore, I suspected a filesystem problem.
I suspected some limitations of MacOs that wasn't in Linux and found some info saying that by default there is only 256 handles available per process. Linux and Windows allow more.
So I looked on handle usage and found that the handles wasn't freed when loading the textures. The 256 handle limit was crossed around the voxeltexture_245.bmp. At this point, I knew I what I had to search for.

We are happy to know that Blackvoxel is compiling with LLVM. It's up to you to see if you want to test it with the 4. There is good chance that this would work.

Thanks, Joshua !
The Blackvoxel Team

**Comment by 0joshuaolson1** [comment]
> Do you agree we mention your name in it ?

Sure!

> can you fill it and submit a new pull request for the updated Contributors.txt ?

Will do.

The file limit makes sense - that's a lot of leaked resources.

With LLVM 4 I'm getting errors from ZString.h about undefined identifiers, so I'll be working on that after I PR Contributors.txt.

**Pull request merged**
